apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
   app: webserver-pod
   region: IN
   rack: r1
   version: "1.1"
spec:
  containers:
    - name: hello-world-web-server
      image: hello-world
      ports:
      - containerPort: 80
